apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: foodcatalogue-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:tusharV07/food-ordering-cloud-native-k8s.git
    targetRevision: main
    path: k8s/aws
    directory:
      include: 'food-catalogue-manifest.yml'
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
